# Generated by Django 4.0 on 2022-01-08 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jokes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('text', models.TextField()),
                ('rate', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'جوک',
                'verbose_name_plural': 'جوک ها',
            },
        ),
    ]
