# Generated by Django 4.0 on 2022-01-16 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs_module', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=40)),
                ('temp', models.FloatField()),
            ],
            options={
                'verbose_name': 'آب و هوا',
                'verbose_name_plural': 'آب و هوا ها',
            },
        ),
    ]
