# Generated by Django 4.0 on 2022-01-22 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs_module', '0002_weather'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Weather',
        ),
    ]
