# Generated by Django 4.0 on 2022-01-10 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_module', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='users',
            options={'verbose_name': 'کاربر', 'verbose_name_plural': 'کاربران'},
        ),
    ]
