# Generated by Django 4.0 on 2022-01-11 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_module', '0002_alter_users_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
