# Generated by Django 4.0 on 2022-01-21 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_module', '0003_users_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='images'),
        ),
    ]
