# Generated by Django 4.0 on 2022-01-22 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_module', '0004_users_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='profile_images'),
        ),
    ]
