# Generated by Django 4.0 on 2022-02-15 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_module', '0007_remove_users_slug_users_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='users',
            name='email_verification_code',
            field=models.CharField(max_length=72, null=True),
        ),
    ]
