# Generated by Django 4.0 on 2022-02-15 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_module', '0008_users_is_active_alter_users_email_verification_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='email_verification_code',
            field=models.CharField(blank=True, max_length=72, null=True),
        ),
    ]
