# Generated by Django 4.0.3 on 2022-03-13 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_module', '0009_alter_users_email_verification_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='email_verification_code',
            new_name='verification_code',
        ),
    ]
