# Generated by Django 4.0 on 2022-01-03 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='H',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان')),
                ('description', models.CharField(max_length=500, verbose_name='حقیقت')),
                ('punishment', models.CharField(max_length=500, verbose_name='مجازات')),
            ],
            options={
                'verbose_name': 'حقیقت',
                'verbose_name_plural': 'حقیقت ها',
            },
        ),
        migrations.CreateModel(
            name='J',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان')),
                ('description', models.CharField(max_length=500, verbose_name='جرعت')),
                ('punishment', models.CharField(max_length=500, verbose_name='مجازات')),
            ],
            options={
                'verbose_name': 'جرعت',
                'verbose_name_plural': 'جرعت ها',
            },
        ),
    ]
