# Generated by Django 4.0 on 2022-01-08 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games_module', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='h',
            name='description',
            field=models.TextField(max_length=500, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='j',
            name='description',
            field=models.TextField(max_length=500, verbose_name='توضیحات'),
        ),
    ]
