# Generated by Django 4.0.3 on 2022-03-17 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('short_name', models.CharField(max_length=100)),
                ('base_url', models.URLField()),
                ('about_us', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('copy_right', models.TextField()),
                ('logo', models.ImageField(null=True, upload_to='logo')),
                ('main_settings', models.BooleanField()),
            ],
            options={
                'verbose_name': 'تنظیمات',
                'verbose_name_plural': 'تنظیمات ها',
            },
        ),
    ]
