# Generated by Django 4.0.3 on 2022-03-17 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_module', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sitesettings',
            old_name='main_settings',
            new_name='main',
        ),
    ]
