# Generated by Django 4.0 on 2022-02-11 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HypeMusics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('artist', models.CharField(max_length=50)),
                ('song_track', models.FileField(upload_to='musics/hype')),
            ],
        ),
        migrations.CreateModel(
            name='OldMusics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('artist', models.CharField(max_length=50)),
                ('song_track', models.FileField(upload_to='musics/old')),
            ],
        ),
        migrations.CreateModel(
            name='SadMusics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('artist', models.CharField(max_length=50)),
                ('song_track', models.FileField(upload_to='musics/sad')),
            ],
        ),
    ]
