# Generated by Django 4.0 on 2022-02-11 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('musics_module', '0002_artis_alter_hypemusics_artist'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artis',
            options={'verbose_name': 'هنرمند', 'verbose_name_plural': 'هنرمندان'},
        ),
        migrations.AlterModelOptions(
            name='hypemusics',
            options={'verbose_name': 'آهنگ شاد', 'verbose_name_plural': 'آهنگ های شاد'},
        ),
        migrations.AlterModelOptions(
            name='oldmusics',
            options={'verbose_name': 'آهنگ قدیمی', 'verbose_name_plural': 'آهنگ های قدیمی'},
        ),
        migrations.AlterModelOptions(
            name='sadmusics',
            options={'verbose_name': 'آهنگ غمگین', 'verbose_name_plural': 'آهنگ های غمگین'},
        ),
        migrations.AlterField(
            model_name='oldmusics',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musics_module.artis'),
        ),
        migrations.AlterField(
            model_name='sadmusics',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musics_module.artis'),
        ),
    ]
