# Generated by Django 4.0 on 2022-01-10 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login_module', '0002_alter_users_options'),
        ('panels_module', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='panels',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_panel', to='login_module.users'),
        ),
    ]
