# Generated by Django 4.0 on 2022-01-11 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panels_module', '0002_alter_panels_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='panels',
            options={'verbose_name': 'پنل', 'verbose_name_plural': 'پنل ها'},
        ),
        migrations.AddField(
            model_name='panels',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
