# Generated by Django 4.0 on 2022-01-21 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panels_module', '0003_alter_panels_options_panels_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='panels',
            name='slug',
        ),
    ]
