# Generated by Django 4.0 on 2022-02-13 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panels_module', '0004_remove_panels_slug'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Panels',
        ),
    ]
